### ISSUE TITLE
slovene data: noway,dude normalization

### ISSUE THREAD

**Issue by simon-clematide** [coastalcph/histnorm#1]
The Slovene datasets have a number of strange normalizations with "no_way,_dude".
Does this come from the original dataset? 

```
grep -cR "no_way,_dude"  *
slovene/slovene-goo300k-gaj.dev.txt:73
slovene/slovene-goo300k-bohoric.test.txt:34
slovene/slovene-goo300k-bohoric.dev.txt:37
slovene/slovene-goo300k-gaj.test.txt:74
slovene/slovene-goo300k-bohoric.train.txt:0
slovene/slovene-goo300k-gaj.train.txt:0
```

**Comment by mbollmann** [comment]
Yes, it does.

I was informed that this was a way to encode multi-word expressions that were not seen in the training data and could therefore not be handled by a token-level normalization approach, as they would require token splitting/joining.

**Comment by simon-clematide** [comment]
ok, and you kept them for your evaluation? Given that they occur in the dev set, they might disturb model selection slightly.

**Comment by mbollmann** [comment]
Yes, I believe I kept them everywhere.
