### ISSUE TITLE
Raw accuracy numbers for training size ablation experiments of Figure 3

### ISSUE THREAD

**Issue by simon-clematide** [coastalcph/histnorm#3]
The figure3 has plots for the accuracy for different training set sizes. Would it be possible to get the raw numbers that went into the plot. It is a bit difficult to reengineer the numbers from the images....

**Comment by mbollmann** [comment]
Sorry for the late reply, I've been busy with conferences, and this needed a bit of digging.

I've now added a PDF to the repo with the raw numbers.

**Comment by mbollmann** [comment]
Direct link:
https://github.com/coastalcph/histnorm/blob/master/appendix_tab6.pdf

**Comment by simon-clematide** [comment]
Great, thanks a lot!
